---
plugins:
   - "@semantic-release/commit-analyzer"
   - "@semantic-release/release-notes-generator"
   - "@semantic-release/github"
#  - - "@semantic-release/commit-analyzer"
#    - preset: eslint
#  - - "@semantic-release/release-notes-generator"
#    - preset: eslint

preset: eslint
success: false
fail: false
npmPublish: false
tarballDir: false
tagFormat: "${version}"
